-- ORACLE DDL SCRIPT for Shedlock

CREATE TABLE SHEDLOCK
(
    NAME       VARCHAR2(64)  NOT NULL PRIMARY KEY,
    LOCK_UNTIL TIMESTAMP(3)  NOT NULL,
    LOCKED_AT  TIMESTAMP(3)  NOT NULL,
    LOCKED_BY  VARCHAR2(255) NOT NULL
);

-- INDEXES
CREATE INDEX IDX_SHEDLOCK_LOCK_UNTIL ON SHEDLOCK (LOCK_UNTIL);
CREATE INDEX IDX_SHEDLOCK_LOCKED_AT ON SHEDLOCK (LOCKED_AT);
CREATE INDEX IDX_SHEDLOCK_LOCKED_BY ON SHEDLOCK (LOCKED_BY);