spring:
  application:
    name: qoop-outbox-app

  datasource:
    url: jdbc:postgresql://localhost:5432/outbox_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  data:
    redis:
      host: localhost
      port: 6379

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

outbox:
  publisher-mode: batch
  fixed-delay: 2000

  cleanup:
    enabled: true
    cron: 0 0 3 * * *
    retention-days: 1

batch:
  partition:
    strategy:
      force-local: false
    grid-size: 4
    chunk-size: 10

kafka:
  enabled: true
  bootstrap-servers: localhost:9092

cluster:
  heartbeat:
    ttl-seconds: 60
    interval-seconds: 20

logging:
  level:
    io.qoop: DEBUG
    org.springframework.batch: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE