-- ORACLE DDL SCRIPT (COMPLETE)

CREATE TABLE OUTBOX_EVENT
(
    ID            RAW(16)      DEFAULT SYS_GUID() PRIMARY KEY,
    AGGREGATETYPE VARCHAR2(100)                          NOT NULL,
    AGGREGATEID   VARCHAR2(100)                          NOT NULL,
    TYPE          VARCHAR2(500)                          NOT NULL,
    TOPIC         VARCHAR2(200)                          NOT NULL,
    PAYLOAD       CLOB                                   NOT NULL,
    HEADERS       CLOB,
    STATUS        VARCHAR2(20) DEFAULT 'NEW'             NOT NULL,
    RETRY_COUNT   NUMBER(10)   DEFAULT 0                 NOT NULL,
    VERSION       NUMBER(19)   DEFAULT 0                 NOT NULL,
    CREATED_AT    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    SENT_AT       TIMESTAMP,
    CONSTRAINT CHK_OUTBOX_PAYLOAD_JSON CHECK (PAYLOAD IS JSON),
    CONSTRAINT CHK_OUTBOX_HEADERS_JSON CHECK (HEADERS IS JSON)
);

CREATE TABLE OUTBOX_ERROR_MESSAGE
(
    ID              RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    TOPIC           VARCHAR2(200),
    KEY             VARCHAR2(200),
    PAYLOAD         CLOB,
    ERROR_MESSAGE   VARCHAR2(2000),
    EXCEPTION_CLASS VARCHAR2(500),
    STACK_TRACE     CLOB,
    CORRELATION_ID  VARCHAR2(100),
    TIMESTAMP       TIMESTAMP WITH TIME ZONE,
    CONSTRAINT CHK_ERR_PAYLOAD_JSON CHECK (PAYLOAD IS JSON)
);

-- INDEXES
CREATE INDEX IDX_OUTBOX_STATUS_CREATED ON OUTBOX_EVENT (STATUS, CREATED_AT);
CREATE INDEX IDX_OUTBOX_AGGREGATE ON OUTBOX_EVENT (AGGREGATETYPE, AGGREGATEID);
CREATE INDEX IDX_OUTBOX_TOPIC ON OUTBOX_EVENT (TOPIC);
CREATE INDEX IDX_OUTBOX_ERROR_CORR ON OUTBOX_ERROR_MESSAGE (CORRELATION_ID);
CREATE INDEX IDX_OUTBOX_ERROR_TIME ON OUTBOX_ERROR_MESSAGE (TIMESTAMP);