package io.qoop.fault.handler.api.exception;

/**
 * @author Davood Akbari - 1404
 * daak1365@gmail.com
 * daak1365@yahoo.com
 * 09125188694
 */

public interface ExceptionCode {
    String INTERNAL_ERROR = "INTERNAL_ERROR";
    String EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR";
    String BAD_REQUEST_ERROR = "BAD_REQUEST_ERROR";
    String UNAUTHORIZED_ERROR = "UNAUTHORIZED_ERROR";
    String FORBIDDEN_ERROR = "FORBIDDEN_ERROR";
    String NOT_FOUND_ERROR = "NOT_FOUND_ERROR";
    String REQUEST_TIMEOUT_ERROR = "REQUEST_TIMEOUT_ERROR";
    String TOO_MANY_REQUESTS_ERROR = "TOO_MANY_REQUESTS_ERROR";
    String BAD_GATEWAY_ERROR = "BAD_GATEWAY_ERROR";
    String SERVICE_UNAVAILABLE_ERROR = "SERVICE_UNAVAILABLE_ERROR";
    String GATEWAY_TIMEOUT_ERROR = "GATEWAY_TIMEOUT_ERROR";
    String VALIDATION_FAILED = "VALIDATION_FAILED";
    String CONSTRAINT_VIOLATION = "CONSTRAINT_VIOLATION";
}
