<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.qoop</groupId>
        <artifactId>qoop-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../qoop-parent/pom.xml</relativePath>
    </parent>

    <artifactId>qoop-container</artifactId>

    <packaging>pom</packaging>

    <properties>
        <security.profile>no-security</security.profile>
    </properties>

    <profiles>
        <profile>
            <id>e-development</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <spring.profiles.active>development</spring.profiles.active>
            </properties>
        </profile>

        <profile>
            <id>e-test</id>
            <properties>
                <spring.profiles.active>test</spring.profiles.active>
            </properties>
        </profile>

        <profile>
            <id>e-stage</id>
            <properties>
                <spring.profiles.active>stage</spring.profiles.active>
            </properties>
        </profile>

        <profile>
            <id>e-production</id>
            <properties>
                <spring.profiles.active>production</spring.profiles.active>
            </properties>
        </profile>

        <profile>
            <id>ch-checker</id>

            <dependencies>
                <dependency>
                    <groupId>io.qoop</groupId>
                    <artifactId>qoop-checker</artifactId>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>c-resource-open-api-doc</id>

            <dependencies>
                <dependency>
                    <groupId>io.qoop</groupId>
                    <artifactId>qoop-resource-open-api-doc</artifactId>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>c-gateway-open-api-doc</id>

            <dependencies>
                <dependency>
                    <groupId>io.qoop</groupId>
                    <artifactId>qoop-gateway-open-api-doc</artifactId>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>c-logging</id>

            <dependencies>
                <dependency>
                    <groupId>io.qoop</groupId>
                    <artifactId>qoop-logs-core</artifactId>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>c-eureka-client-discovery</id>

            <dependencies>
                <dependency>
                    <groupId>io.qoop</groupId>
                    <artifactId>qoop-eureka-client-discovery</artifactId>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>c-consul-client-discovery</id>

            <dependencies>
                <dependency>
                    <groupId>io.qoop</groupId>
                    <artifactId>qoop-consul-client-discovery</artifactId>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>c-fault-handler-rest</id>

            <dependencies>
                <dependency>
                    <groupId>io.qoop</groupId>
                    <artifactId>qoop-fault-handler-rest</artifactId>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>c-jwt-resource-security</id>

            <properties>
                <security.profile>jwt</security.profile>
            </properties>

            <dependencies>
                <dependency>
                    <groupId>io.qoop</groupId>
                    <artifactId>qoop-resource-security</artifactId>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>c-opaque-resource-security</id>

            <properties>
                <security.profile>opaque</security.profile>
            </properties>

            <dependencies>
                <dependency>
                    <groupId>io.qoop</groupId>
                    <artifactId>qoop-resource-security</artifactId>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>c-gateway-security</id>

            <dependencies>
                <dependency>
                    <groupId>io.qoop</groupId>
                    <artifactId>qoop-gateway-security</artifactId>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>c-response-unifier</id>

            <dependencies>
                <dependency>
                    <groupId>io.qoop</groupId>
                    <artifactId>qoop-response-unifier</artifactId>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>c-bean-filter</id>

            <dependencies>
                <dependency>
                    <groupId>io.qoop</groupId>
                    <artifactId>qoop-bean-filter-core</artifactId>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>c-transactional</id>

            <dependencies>
                <dependency>
                    <groupId>io.qoop</groupId>
                    <artifactId>qoop-transaction-core</artifactId>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>c-validation</id>

            <dependencies>
                <dependency>
                    <groupId>io.qoop</groupId>
                    <artifactId>qoop-validation-core</artifactId>
                </dependency>
            </dependencies>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <systemPropertyVariables>
                        <spring.profiles.active>${spring.profiles.active}</spring.profiles.active>
                    </systemPropertyVariables>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <finalName>${project.artifactId}-${project.version}</finalName>
                    <outputDirectory>${basedir}/output</outputDirectory>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
