<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.qoop</groupId>
    <artifactId>qoop-bom</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <!-- Version properties for all dependencies -->
        <qoop.version>0.0.1-SNAPSHOT</qoop.version>
        <qoop-event-stream.version>0.0.1-SNAPSHOT</qoop-event-stream.version>
        <qoop-security-api>0.0.1-SNAPSHOT</qoop-security-api>
        <qoop-logs.version>0.0.1-SNAPSHOT</qoop-logs.version>
        <qoop-messages.version>0.0.1-SNAPSHOT</qoop-messages.version>
        <qoop-security-starter.version>0.0.1-SNAPSHOT</qoop-security-starter.version>
        <qoop-resource-open-api-doc.version>0.0.1-SNAPSHOT</qoop-resource-open-api-doc.version>
        <qoop-logs.version>0.0.1-SNAPSHOT</qoop-logs.version>
        <qoop-fault-handler-rest.version>0.0.1-SNAPSHOT</qoop-fault-handler-rest.version>
        <qoop-resource-security.version>0.0.1-SNAPSHOT</qoop-resource-security.version>
        <qoop-checker.version>0.0.1-SNAPSHOT</qoop-checker.version>
        <qoop-eureka-client-discovery.version>0.0.1-SNAPSHOT</qoop-eureka-client-discovery.version>
        <qoop-consul-client-discovery.version>0.0.1-SNAPSHOT</qoop-consul-client-discovery.version>
        <qoop-response-unifier.version>0.0.1-SNAPSHOT</qoop-response-unifier.version>
        <qoop-gateway-security.version>0.0.1-SNAPSHOT</qoop-gateway-security.version>
        <qoop-validation-api.version>0.0.1-SNAPSHOT</qoop-validation-api.version>
        <qoop-validation-core.version>0.0.1-SNAPSHOT</qoop-validation-core.version>
        <qoop-gateway-open-api-doc.version>0.0.1-SNAPSHOT</qoop-gateway-open-api-doc.version>

        <!-- External dependencies -->
        <java.version>21</java.version>
        <spring-cloud.version>2025.1.0</spring-cloud.version>
        <springdoc-openapi-starter-webmvc-ui.version>3.0.0</springdoc-openapi-starter-webmvc-ui.version>
        <spring-boot-starter-aop.version>4.0.0-M2</spring-boot-starter-aop.version>
        <logback-gelf.version>6.1.2</logback-gelf.version>
        <jjwt.version>0.12.6</jjwt.version>
        <gelfclient.version>1.5.1</gelfclient.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <lombok.version>1.18.34</lombok.version>
        <lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- Spring Cloud -->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- SpringDoc OpenAPI -->
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${springdoc-openapi-starter-webmvc-ui.version}</version>
            </dependency>

            <!-- Spring Boot AOP -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-aop</artifactId>
                <version>${spring-boot-starter-aop.version}</version>
            </dependency>

            <!-- MapStruct -->
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${mapstruct.version}</version>
                <scope>provided</scope>
            </dependency>

            <!-- Lombok -->
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok-mapstruct-binding</artifactId>
                <version>${lombok-mapstruct-binding.version}</version>
                <scope>provided</scope>
            </dependency>

            <!-- JWT -->
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-api</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-impl</artifactId>
                <version>${jjwt.version}</version>
                <scope>runtime</scope>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-jackson</artifactId>
                <version>${jjwt.version}</version>
                <scope>runtime</scope>
            </dependency>

            <!-- Logging -->
            <dependency>
                <groupId>org.graylog2</groupId>
                <artifactId>gelfclient</artifactId>
                <version>${gelfclient.version}</version>
            </dependency>
            <dependency>
                <groupId>de.siegmar</groupId>
                <artifactId>logback-gelf</artifactId>
                <version>${logback-gelf.version}</version>
            </dependency>

            <!-- Internal Dependencies -->
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-checker</artifactId>
                <version>${qoop-checker.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-resource-open-api-doc</artifactId>
                <version>${qoop-resource-open-api-doc.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-gateway-open-api-doc</artifactId>
                <version>${qoop-gateway-open-api-doc.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-eureka-client-discovery</artifactId>
                <version>${qoop-eureka-client-discovery.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-consul-client-discovery</artifactId>
                <version>${qoop-consul-client-discovery.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-logs-api</artifactId>
                <version>${qoop-logs.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-logs-core</artifactId>
                <version>${qoop-logs.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-messages</artifactId>
                <version>${qoop-messages.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-security-starter</artifactId>
                <version>${qoop-security-starter.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-security-api</artifactId>
                <version>${qoop-security-api}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-resource-security</artifactId>
                <version>${qoop-resource-security.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-gateway-security</artifactId>
                <version>${qoop-gateway-security.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-response-unifier</artifactId>
                <version>${qoop-response-unifier.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-mapper-api</artifactId>
                <version>${qoop.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-mapper-core</artifactId>
                <version>${qoop.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-yml-property</artifactId>
                <version>${qoop.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-property-api</artifactId>
                <version>${qoop.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-utils-api</artifactId>
                <version>${qoop.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-application</artifactId>
                <version>${qoop.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-domain</artifactId>
                <version>${qoop.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-transaction-api</artifactId>
                <version>${qoop.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-fault-handler-api</artifactId>
                <version>${qoop.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-fault-handler-rest</artifactId>
                <version>${qoop-fault-handler-rest.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-validation-api</artifactId>
                <version>${qoop-validation-api.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-validation-core</artifactId>
                <version>${qoop-validation-core.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-messages-api</artifactId>
                <version>${qoop.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-messages-core</artifactId>
                <version>${qoop.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-transaction-core</artifactId>
                <version>${qoop.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-bean-filter-api</artifactId>
                <version>${qoop.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-bean-filter-core</artifactId>
                <version>${qoop.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-validation</artifactId>
                <version>${qoop.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-event-stream-api</artifactId>
                <version>${qoop-event-stream.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-event-stream-publisher</artifactId>
                <version>${qoop-event-stream.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-event-stream-subscriber</artifactId>
                <version>${qoop-event-stream.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-data-jpa-api</artifactId>
                <version>${qoop.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qoop</groupId>
                <artifactId>qoop-data-jpa-core</artifactId>
                <version>${qoop.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>